In [5]:
# Imports need for notebook
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import warnings
warnings.filterwarnings("ignore")

__Delete this cell later__:

---

idea for structuring the text in notebook: We could do something like this:
 - Start by saying "we have done x, y & Z know ...", "based on the load data we can know do x..." and etc..
 - Do the next step/task.
 - Finish each thing with *Answer:* "We found that ..."

---

## 1. Bussiness case / Problem statement

A cross the world, we all use cars, som places more then others, which leads to a lot cars being bought and sold. According to S&P Global, there was in 
"April 2025 US auto sales in April expected to reach 1.49 million units [...]" source: [automotive-insights](https://www.spglobal.com/automotive-insights/en/blogs/2025/02/us-auto-sales-2025). Where there is a lot of cars being sold, they often can end up at used car dealerships, which there are a large amount of according to [ibisworld](https://www.ibisworld.com/united-states/number-of-businesses/used-car-dealers/1004/), where "[...] 130,152 Used Car Dealers in the US businesses as of 2023, an decrease of -0.6% from 2022.", based on this we can wonder how can these used car dealerships price their cars? What factors are important and make weight in the pricing of a car? Can this be done more efficiently by using machine learning? And if so, how?

## 2. Data selection and preparation:

This section will include:
- x
- y


This exam project is based on the dataset(s): [Car Prices Dataset](https://www.kaggle.com/datasets/sidharth178/car-prices-dataset?select=train.csv) from kaggle. This contains two  datasets: test.csv and train.csv, where the test set dont contain price. These sets of data don't seem to have been pre cleaned. A thing to consider is that if the test.csv is to close to the train.csv, it might give some bias in the model and fit it to well, so we need to be careful with that.

### 2.1 Load data

In [9]:
base_path = '../data/'

df_test = pd.read_csv(base_path + 'test.csv', sep=',', header=0)
df = pd.read_csv(base_path + 'train.csv', sep=',', header=0)

We will load the data using pandas read_csv function, where we have specified the separator to separate by sep = ',' and with header = 0 to instruct that the first row of the csv file is a header, wich will become the columns in the dataframe.

After the data has been loaded, we verify that the data has been loadded properly by sampling 5 ranomd rows of the data, by using the sample function:

In [16]:
df.sample(5)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
4870,45756447,6272,-,MERCEDES-BENZ,C 180,1995,Sedan,No,Petrol,1.8,100000 km,4.0,Manual,Rear,04-May,Left wheel,Green,0
18589,45781568,12544,-,BMW,530,2006,Sedan,Yes,Petrol,3,264000 km,6.0,Tiptronic,Rear,04-May,Left wheel,Black,10
14238,45771076,9565,1091,TOYOTA,RAV 4,2016,Jeep,Yes,Petrol,2.5,60677 km,4.0,Automatic,Front,04-May,Left wheel,Grey,12
8074,45733664,57698,1079,HYUNDAI,Sonata,2018,Sedan,Yes,Petrol,2,36304 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
356,45801349,5300,-,HONDA,Stream,2001,Universal,No,Petrol,2,111000 km,4.0,Automatic,Front,04-May,Right-hand drive,Black,6

In [13]:
df_test.sample(5)

,ID,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Price
1583,45524892,1077,TOYOTA,CHR,2019,Jeep,Yes,Petrol,2,78424 km,4,Automatic,Front,04-May,Left wheel,Red,12,NaN
2487,45744790,836,DAEWOO,Lacetti,2010,Sedan,Yes,Diesel,2,47221 km,4,Automatic,Front,04-May,Left wheel,Black,4,NaN
6513,45725071,836,SSANGYONG,Actyon,2010,Jeep,Yes,Diesel,2,128668 km,4,Automatic,Front,04-May,Left wheel,Silver,4,NaN
651,45769875,1172,MERCEDES-BENZ,E 350,2011,Sedan,Yes,Diesel,3.5,230696 km,6,Automatic,4x4,04-May,Left wheel,Black,12,NaN
1116,45647008,1292,MERCEDES-BENZ,E 400,2016,Cabriolet,Yes,Petrol,3,0 km,6,Automatic,Rear,02-Mar,Left wheel,White,12,NaN

We can see that the data has been loaded properly. Additionally this process also helps us to quickly get a view and idea of the data we are going to work with. We can first of all see that the `ID` column is not need beacuse the datafram has its own bulid in index. Secondly we can see that the `Doors`column looks a bit strange, beacause it containes 3 opstions: '04-May', '02-Mar' or '>5', which couold be a mistake in the data, so this has to be checked more in detail.

### 2.2 Cleaning- and Preprocessing Data

After we have loadede the data we have observed ...

In [ ]:
# Clean up the data

###

In [ ]:
## remove 
df.drop(columns=['id'], inplace=True)
df_test.drop(columns=['id'], inplace=True)

#### 2.x.x Verifying data after cleaning

Just in case, we check if the values have been drop, so we don't end with unexpected values in the data. We do this as we did after loading the data, by randomly sampling 5 rows from the datasets.

In [14]:
df.sample(5)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
17905,45788974,4704,-,OPEL,Astra,1998,Sedan,No,Petrol,1.6,333333 km,4.0,Manual,Front,04-May,Left wheel,Grey,0
19165,45797295,17634,531,HYUNDAI,I30,2012,Hatchback,Yes,Diesel,1.6,183380 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4
15207,45761840,16305,562,FIAT,500,2015,Hatchback,Yes,Petrol,1.4,64000 km,4.0,Automatic,Front,02-Mar,Left wheel,White,10
7634,45776695,14500,697,VOLKSWAGEN,Jetta,2015,Sedan,No,Petrol,1.8 Turbo,56000 km,4.0,Tiptronic,Front,04-May,Left wheel,White,8
3682,45806815,18817,645,TOYOTA,Prius,2011,Sedan,Yes,Hybrid,1.8,178000 km,4.0,Variator,Front,04-May,Left wheel,Grey,6

In [15]:
df_test.sample(5)

,ID,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags,Price
6827,45597113,-,BMW,328,2011,Sedan,Yes,Petrol,3,112000 km,4,Automatic,Rear,04-May,Left wheel,Silver,6,NaN
2873,45729718,530,HYUNDAI,Elantra,2013,Sedan,Yes,Petrol,1.6,92746 km,4,Automatic,Front,04-May,Left wheel,Grey,4,NaN
7824,45786620,1268,TOYOTA,Aqua,2012,Hatchback,No,Hybrid,1.5,103000 km,4,Automatic,Front,04-May,Right-hand drive,Silver,2,NaN
6770,45115080,753,CHEVROLET,Malibu,2012,Sedan,No,Hybrid,2.4,123000 km,4,Tiptronic,Front,04-May,Left wheel,White,8,NaN
2633,45815050,934,TOYOTA,RAV 4,2015,Jeep,Yes,Petrol,2.5,83896 km,4,Automatic,4x4,04-May,Left wheel,Grey,12,NaN

We can know comfirm that the values have infact been droped, and that the data is cleaned. 

Lastly we save the cleaned data to a new csv file ...

In [17]:
# save to new csv files

## 3 Data exploration and visualization:

This section will include:
- x
- y



--- 
Look at the data and try to understand it. What are the most important features?

Make some visualizations to understand the data better, by showing the distribution of the features and the target variable.

Try to find correlations between the features and the target variable, by making scatter plots and correlation matrices.

etc ...

## 4. Model Selection and training:

This section will include:
- x
- y

### 4.1 The selected model(s)

We have selected the following models for this project:
- Multiple Linear Regression
- Model 2

The reason for the selected models is as follows:
- Multiple Linear Regression: ..
- Model 2: This model is selected because ...

We are going to be using the following error metrics to evalaute the models:
- x
- y
- z

Additionaly we are going to be useing the grid search approach for ...

### 4.2 Model training and validation

Based on the selected models we have trained the models using the training data. The training process is as follows:

"describe the training process here, that we are going to use and why that makes sence"

### 4.3 Model evaluation